version: "2"

services:
  composite-service:
    build: composite-service
    image: local/composite-service
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - service-1
      - service-2
    links:
      - service-1:service-1
      - service-2:service-2
      - config-server:config-server

  service-1:
    build: service-1
    image: local/service-1
    depends_on:
      - config-server
      - edge-server
      - monitor-dashboard
      - zipkin-server
      - rabbitmq
      - auth-server
    links:
      - config-server:config-server

  service-2:
    build: service-2
    image: local/service-2
    depends_on:
      - config-server
    links:
      - config-server:config-server

  edge-server:
    build: background-services/edge-server
    image: local/edge-server
    ports:
      - "8765:8765"
    depends_on:
      - auth-server
      - rabbitmq
    links:
      - "auth-server:auth-server"
      - "rabbitmq:rabbitmq"

  monitor-dashboard:
    build: background-services/monitor-dashboard
    image: local/monitor-dashboard
    ports:
      - "7979:7979"

  zipkin-server:
    build: background-services/zipkin-server
    image: local/zipkin-server
    ports:
      - "9411:9411"
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"

  config-server:
    build: background-services/config-server
    image: local/config-server
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"

  auth-server:
    build: background-services/auth-server
    image: local/auth-server
    ports:
      - "9999:9999"
    depends_on:
      - rabbitmq
    links:
      - "rabbitmq:rabbitmq"
