version: "3"

services:
  composite-service:
    image: local/composite-service
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - service-1
      - service-2
    deploy:
      replicas: 1

  service-1:
    image: local/service-1
    depends_on:
      - config-server
      - edge-server
      - monitor-dashboard
      - zipkin-server
      - rabbitmq
      - auth-server
    deploy:
      replicas: 1

  service-2:
    image: local/service-2
    depends_on:
      - config-server
      - edge-server
      - monitor-dashboard
      - zipkin-server
      - rabbitmq
      - auth-server
    deploy:
      replicas: 1

  edge-server:
    image: local/edge-server
    ports:
      - "8765:8765"
    depends_on:
      - auth-server
      - rabbitmq
    deploy:
      replicas: 1

  monitor-dashboard:
    image: local/monitor-dashboard
    ports:
      - "7979:7979"
    deploy:
      replicas: 1

  zipkin-server:
    image: local/zipkin-server
    ports:
      - "9411:9411"
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  config-server:
    image: local/config-server
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  auth-server:
    image: local/auth-server
    ports:
      - "9999:9999"
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    deploy:
      replicas: 1
