server.port: 8888

# Sample configuration of an external Git-repo
#spring.cloud.config.server.git.uri: https://github.com/callistaenterprise/blog-microservices-config.git

# Configuration of a local Git-repo
spring.cloud.config.server.git.uri: $PWD/config-repo
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672

# 1.0 means 100%, see http://cloud.spring.io/spring-cloud-sleuth/spring-cloud-sleuth.html#_sampling
spring.sleuth.sampler.percentage: 1.0

logging:
  level:
    root: WARN
    se.callista: INFO

    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO
    org.apache.catalina.session.ManagerBase: INFO

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO


---
# For deployment in Docker containers
spring:
  profiles: docker

spring.cloud.config.server.git.uri: /config-repo

spring.rabbitmq.host: rabbitmq
